#!/usr/bin/env python3
"""md2tex.py -- regenerate the PSIThesis LaTeX sources from ../draft_v5_en.

The .tex files under chapters/, appendices/ and front/ and literature.bib are
GENERATED by this script. Edit the Markdown in manuscript/draft_v5_en/ and
re-run; hand edits to the generated files are overwritten.

    python md2tex.py            regenerate every .tex file and literature.bib
    python md2tex.py --figures  also copy the referenced figures into ./figures
    python md2tex.py --zip      regenerate, collect figures and write
                                ../thesis-psithesis-overleaf.zip

No third-party packages: runs on the plain Python of the Windows authoring
host as well as on the compute host.

What the conversion does, in the order it matters for the typeset result:

* Structure. "# Chapter N -- Title" becomes \\chapter + \\label{ch:NN},
  "# Appendix X -- Title" \\chapter + \\label{app:X}; numbered headings get
  \\label{sec:<number as written>}, so "§7.2.4" in the prose resolves.
* Citations. "(Author et al., 2025)" becomes \\cite{key}; the narrative form
  "Author et al. (2025)" keeps the names as written and replaces only the year
  with \\cite{key}. Keys come from the same parse of 0_bibliography.md that
  writes literature.bib, so a citation that does not resolve is reported.
* Cross references. "Chapter 8", "Figure 7.1", "Table F.1", "Appendix G" and
  "§9.3.6" link to their labels; the words stay as the author wrote them.
* Identifiers. H-XX, SR-XXX, C-XX, SC-*-XX, M-*, D-NN go through the macros
  of misc/thesis-commands.tex, which never break across a line.
* Tables. The layout is computed from the content, see layout_table(). Body
  tables that do not fit the 107 mm text column become table* floats over
  text + margin (164.6 mm). Appendix tables are longtables with a repeated
  header over the full-width appendix geometry that main.tex switches to,
  because a page-breaking table cannot follow the margin column from odd to
  even pages -- that was the defect of the hand conversion.
"""

from __future__ import annotations

import argparse
import math
import re
import shutil
import sys
import unicodedata
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "draft_v5_en"
FIG_POOL = HERE.parent / "figures"
ZIP_OUT = HERE.parent / "thesis-psithesis-overleaf.zip"

WARNINGS: list[str] = []


def warn(msg: str) -> None:
    WARNINGS.append(msg)


# ---------------------------------------------------------------------------
# Geometry of the PSIThesis layout (PSIThesis.cls and main.tex)
# ---------------------------------------------------------------------------
TEXT_MM = 107.0            # \textwidth of the body
WIDE_MM = 107.0 + 8.2 + 49.4  # \widefigurewidth = text + sep + margin column
APPX_MM = WIDE_MM          # appendix geometry in main.tex: same outer edges
PAGE_TEXT_MM = 235.0       # usable height for a float, roughly

# Average character width (mm) of Cochineal at each size, calibrated on the
# ~72 characters per 107 mm line of the 11 pt body. Iosevka at Scale=0.83 is
# close enough that code does not need its own figure.
CHAR_MM = {"normalsize": 1.49, "small": 1.36, "footnotesize": 1.23, "scriptsize": 1.10}
LINE_MM = {"normalsize": 4.8, "small": 4.3, "footnotesize": 3.9, "scriptsize": 3.4}
TABCOLSEP_PT = 4.0
SEP_MM = TABCOLSEP_PT * 0.3515


# ---------------------------------------------------------------------------
# Bibliography
# ---------------------------------------------------------------------------
def strip_accents(s: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))


def norm_name(s: str) -> str:
    return re.sub(r"[^a-z]", "", strip_accents(s).lower())


PROCEEDINGS_HINTS = (
    "Conference", "Symposium", "Workshop", "Forum", "Proceedings", "Advances in",
    "Intelligent Data Engineering", "(ICLR)", "(ICML)", "(ICRA)", "(IROS)", "AAAI",
)


class BibEntry:
    def __init__(self, raw: str):
        self.raw = raw
        m = re.match(r"^\*\*(.+?)\*\*\s*\((\d{4})([a-z]?)\)\.\s*(.*)$", raw)
        if not m:
            raise ValueError(f"unparsed bibliography entry: {raw[:60]}")
        self.author_str, self.year, self.suffix, rest = m.group(1), m.group(2), m.group(3), m.group(4)
        self.authors = self._authors(self.author_str)
        self.first = norm_name(self.authors[0][0])
        self.label_year = self.year + self.suffix
        self._parse_rest(rest.strip())
        self.key = self._key()

    @staticmethod
    def _authors(s: str) -> list[tuple[str, str]]:
        s = s.strip()
        if "," not in s:            # organisation: ISO, ISO/IEC, UL Standards
            return [(s.rstrip("."), "")]
        others = bool(re.search(r",?\s*et al\.?$", s))
        s = re.sub(r",?\s*et al\.?$", "", s)
        s = s.replace(" and ", ", ")
        parts = [p.strip() for p in s.split(",") if p.strip()]
        people = []
        i = 0
        while i < len(parts):
            sur = parts[i]
            ini = parts[i + 1] if i + 1 < len(parts) and re.match(r"^[A-Z]\.", parts[i + 1]) else ""
            ini = ini + ("." if ini and not ini.endswith(".") else "")
            people.append((sur, ini))
            i += 2 if ini else 1
        if others:
            people.append(("others", ""))
        return people

    def _parse_rest(self, rest: str) -> None:
        self.fields: dict[str, str] = {}
        if rest.startswith("*"):
            m = re.match(r"^\*(.+?)\*\s*(.*)$", rest)
            self.title, tail = m.group(1), m.group(2)
            tail = tail.lstrip(".").strip()
            ed = re.match(r"^\((\d)(?:st|nd|rd|th) ed\.\)\.\s*(.*)$", tail)
            if ed:
                self.fields["edition"] = ed.group(1)
                tail = ed.group(2)
            tail = tail.rstrip(".")
            organisation = len(self.authors) == 1 and not self.authors[0][1]
            if ed:
                self.type = "book"
                self.fields["publisher"] = tail
            elif organisation:
                self.type = "manual"
                self.fields["organization"] = tail
            else:
                self.type = "techreport"
                self.fields["institution"] = tail
            return
        m = re.match(r"^(.+?)\.\s+\*(.+?)\*,?\s*(.*)$", rest)
        if not m:
            raise ValueError(f"unparsed bibliography tail: {rest[:60]}")
        self.title, venue, tail = m.group(1), m.group(2), m.group(3).strip().rstrip(".")
        if venue.startswith("arXiv:"):
            self.type = "misc"
            self.fields["eprint"] = venue.split(":", 1)[1]
            self.fields["eprinttype"] = "arxiv"
            return
        if any(h in venue for h in PROCEEDINGS_HINTS):
            self.type = "inproceedings"
            self.fields["booktitle"] = venue
        else:
            self.type = "article"
            self.fields["journal"] = venue
        # tail: "32(1)", "14(13), 2738", "PMLR 78, 1–16", "LNCS 11872, 150–160",
        # "AISC 1409, 508–518. Springer", "2023-2587", "1–8", "31"
        parts = [p.strip() for p in re.split(r",\s*|\.\s+", tail) if p.strip()]
        for p in parts:
            if re.fullmatch(r"\d+–\d+", p):
                self.fields["pages"] = p.replace("–", "--")
            elif m2 := re.fullmatch(r"(\d+)\((\w+)\)", p):
                self.fields["volume"], self.fields["number"] = m2.group(1), m2.group(2)
            elif m2 := re.fullmatch(r"(PMLR|LNCS|AISC) (\d+)", p):
                self.fields["series"], self.fields["volume"] = m2.group(1), m2.group(2)
            elif re.fullmatch(r"\d{1,3}", p) and "volume" not in self.fields:
                self.fields["volume"] = p
            elif re.fullmatch(r"\d{1,3}", p):
                self.fields["eid" if self.type == "article" else "pages"] = p
            elif re.fullmatch(r"\d{4}-\d+", p) or re.fullmatch(r"\d{4,6}", p):
                self.fields["eid" if self.type == "article" else "number"] = p
            elif p == "Springer":
                self.fields["publisher"] = p
            else:
                self.fields["note"] = p

    def _key(self) -> str:
        num = re.search(r"\b(ISO/IEC TR|ISO/PAS|ISO|UL) (\d+)", self.title)
        if num and self.type == "manual":
            prefix = {"ISO/IEC TR": "isotr", "ISO/PAS": "isopas", "ISO": "iso", "UL": "ul"}[num.group(1)]
            return f"{prefix}{num.group(2)}"
        return f"{self.first}{self.year}{self.suffix}"

    def bibtex(self) -> str:
        def esc(v: str) -> str:
            return v.replace("&", r"\&").replace("%", r"\%")

        people = []
        for sur, ini in self.authors:
            if sur == "others":
                people.append("others")
            elif not ini:
                people.append("{" + esc(sur) + "}")
            else:
                people.append(f"{esc(sur)}, {ini}")
        lines = [f"@{self.type}{{{self.key},", f"  author = {{{' and '.join(people)}}},",
                 f"  title  = {{{esc(self.title)}}},", f"  year   = {{{self.year}}},"]
        # biblatex's alphabetic label takes the first three characters of the
        # first surname, which for "De Gelder" or "UL Standards" include a
        # space ("[De +24]"). Give those entries the label without it.
        first_sur = self.authors[0][0]
        if " " in first_sur[:3]:
            named = [a for a in self.authors if a[0] != "others"]
            stem = first_sur.split()[0] if not self.authors[0][1] else first_sur.replace(" ", "")[:3]
            plus = "+" if len(named) > 2 or self.authors[-1][0] == "others" else ""
            if len(named) == 2 and not plus:
                stem = "".join(a[0].replace(" ", "")[0] for a in named)
            lines.append(f"  shorthand = {{{stem}{plus}{self.year[2:]}{self.suffix}}},")
        for k, v in self.fields.items():
            lines.append(f"  {k} = {{{esc(v)}}},")
        lines.append("}")
        return "\n".join(lines)


def load_bibliography() -> list[BibEntry]:
    text = (SRC / "back/0_bibliography.md").read_text(encoding="utf-8")
    entries = [BibEntry(line.strip()) for line in text.splitlines() if line.startswith("**")]
    keys = [e.key for e in entries]
    dup = {k for k in keys if keys.count(k) > 1}
    if dup:
        raise SystemExit(f"duplicate bibliography keys: {sorted(dup)}")
    return entries


# ---------------------------------------------------------------------------
# Markdown blocks
# ---------------------------------------------------------------------------
class Block(dict):
    pass


def parse_blocks(text: str) -> list[Block]:
    lines = text.replace("\r\n", "\n").split("\n")
    blocks: list[Block] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        s = line.strip()
        if not s or re.fullmatch(r"::[a-z-]+::", s) or s == "---":
            i += 1
            continue
        if s.startswith("```"):
            lang = s[3:].strip()
            body = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("```"):
                body.append(lines[i])
                i += 1
            blocks.append(Block(kind="code", lang=lang, lines=body))
            i += 1
            continue
        m = re.match(r"^(#{1,4})\s+(.*)$", s)
        if m:
            blocks.append(Block(kind="heading", level=len(m.group(1)), text=m.group(2).strip()))
            i += 1
            continue
        if s.startswith("<img"):
            src = re.search(r'src="([^"]+)"', s).group(1)
            alt = re.search(r'alt="([^"]*)"', s).group(1)
            width = int(re.search(r'width="(\d+)"', s).group(1))
            blocks.append(Block(kind="img", src=src, alt=alt, width=width))
            i += 1
            continue
        if s.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(lines[i].strip())
                i += 1
            blocks.append(Block(kind="table", rows=rows))
            continue
        if s.startswith(">"):
            paras, cur = [], []
            while i < len(lines) and lines[i].strip().startswith(">"):
                content = lines[i].strip()[1:].strip()
                if content:
                    cur.append(content)
                elif cur:
                    paras.append(" ".join(cur))
                    cur = []
                i += 1
            if cur:
                paras.append(" ".join(cur))
            blocks.append(Block(kind="quote", paras=paras))
            continue
        if re.match(r"^(-|\d+\.)\s+", s):
            ordered = bool(re.match(r"^\d+\.", s))
            items = []
            while i < len(lines) and re.match(r"^\s*(-|\d+\.)\s+", lines[i]):
                items.append(re.sub(r"^\s*(-|\d+\.)\s+", "", lines[i]).strip())
                i += 1
                while i < len(lines) and lines[i].strip() and not re.match(
                        r"^\s*(-|\d+\.)\s+|^\s*[#|<>`]", lines[i]):
                    items[-1] += " " + lines[i].strip()
                    i += 1
            blocks.append(Block(kind="list", ordered=ordered, items=items))
            continue
        para = []
        while i < len(lines) and lines[i].strip() and not re.match(
                r"^\s*(#{1,4}\s|```|<img|\||>|(-|\d+\.)\s)", lines[i]):
            para.append(lines[i].strip())
            i += 1
        blocks.append(Block(kind="para", text=" ".join(para)))
    return blocks


CAPTION_RE = re.compile(r"^\*(Figure|Table)\s+([A-Z0-9]+)\.(\d+)\s+—\s+(.*)\*$", re.S)


# ---------------------------------------------------------------------------
# Documents and labels (pass 1)
# ---------------------------------------------------------------------------
class Doc:
    def __init__(self, md: Path, out: str, kind: str):
        self.md, self.out, self.kind = md, out, kind
        self.blocks = parse_blocks(md.read_text(encoding="utf-8"))
        self.rel = md.relative_to(SRC).as_posix()


def build_docs() -> list[Doc]:
    docs = []
    for md in sorted((SRC / "body").glob("*.md")):
        nn = md.name[:2]
        docs.append(Doc(md, f"chapters/chapter{nn}.tex", "chapter"))
    for md in sorted((SRC / "back").glob("[A-Z]_*.md")):
        docs.append(Doc(md, f"appendices/appendix{md.name[0]}.tex", "appendix"))
    for name, out in (("10_abstract", "front/abstract.tex"), ("15_preface", "front/preface.tex"),
                      ("05_declaration", "front/declaration.tex"),
                      ("40_abbreviations", "front/abbreviations.tex")):
        docs.append(Doc(SRC / "front" / f"{name}.md", out, "front"))
    return docs


def heading_plan(doc: Doc) -> list[tuple[Block, str, str, str]]:
    """Return (block, command, title, label) for every heading of a doc."""
    h1 = [b for b in doc.blocks if b["kind"] == "heading" and b["level"] == 1]
    shift = 1 if len(h1) > 1 else 0
    out = []
    chapter_id = None
    counters = [0, 0, 0]
    first = True
    for b in doc.blocks:
        if b["kind"] != "heading":
            continue
        text = b["text"]
        if first:
            first = False
            m = re.match(r"^(Chapter|Appendix)\s+([A-Z0-9]+)\s+—\s+(.*)$", text)
            if m:
                chapter_id = m.group(2) if m.group(1) == "Appendix" else f"{int(m.group(2)):02d}"
                label = ("app:" if m.group(1) == "Appendix" else "ch:") + chapter_id
                if m.group(1) == "Chapter":
                    chapter_id = str(int(m.group(2)))
                out.append((b, "chapter", m.group(3), label))
            else:
                out.append((b, "addchap", text, ""))
            continue
        depth = b["level"] - 2 + shift        # 0 section, 1 subsection, 2 subsubsection
        depth = max(0, min(2, depth))
        counters[depth] += 1
        for d in range(depth + 1, 3):
            counters[d] = 0
        computed = ".".join([chapter_id or "?"] + [str(c) for c in counters[:depth + 1]])
        m = re.match(r"^([A-Z0-9]+(?:\.\d+)+)\s+(.*)$", text)
        if m:
            number, title = m.group(1), m.group(2)
            if number != computed:
                warn(f"{doc.rel}: heading '{text}' numbered {number}, LaTeX will number it {computed}")
        else:
            number, title = computed, text
        cmd = ("section", "subsection", "subsubsection")[depth]
        out.append((b, cmd, title, f"sec:{number}"))
    return out


# Captions the Markdown does not carry. The appendix registers have none, but
# a longtable without a caption cannot be referenced or listed -- and the text
# does reference "Table F.1". These are supplied here, in one visible place.
SUPPLIED_TABLE_CAPTIONS = {
    ("A", 1): "Hazard register, extended version (full version of Table 4.1).",
    ("B", 1): "Safety requirements with thresholds and traceability (full version of Table 4.2).",
    ("D", 1): "Parameters of the four operational domains.",
    ("D", 2): "Open quantitative questions of the domain and their closure.",
    ("F", 1): "Traceability by mitigation chain, with the simulation verdict.",
    ("F", 2): "Machine-processable form of the traceability matrix.",
    ("G", 1): "Positioning space, complete version (full version of Table 2.1).",
    ("H", 1): "Nominal reward weights.",
    ("H", 2): "Effective hyperparameters of the E-main and F-baseline runs.",
    ("I", 1): "Runs passed by scenario and mode in the reference campaign.",
    ("I", 2): "Status per requirement in the reference campaign.",
    ("I", 3): "Safety invariant in enforcement mode.",
    ("I", 4): "Co-activation grid by domain membership.",
    ("I", 5): "Co-activation grid by combination of rules that fired together.",
}

# Appendix D's two tables have no header row in the Markdown -- the rows start
# with data. Headers supplied from the column contents.
SUPPLIED_TABLE_HEADERS = {
    ("D", 1): ["Parameter", "Meaning", "ODD-1", "ODD-2", "ODD-3", "ODD-4", "Source"],
    ("D", 2): ["ID", "Question", "Owner", "Status", "Resolution"],
}


def figure_and_table_labels(doc: Doc, labels: set[str]) -> None:
    letter = doc.md.name[0] if doc.kind == "appendix" else None
    tcount = 0
    for i, b in enumerate(doc.blocks):
        if b["kind"] == "para":
            m = CAPTION_RE.match(b["text"])
            if m:
                pfx = "fig" if m.group(1) == "Figure" else "tab"
                if pfx == "tab" and letter:
                    continue
                labels.add(f"{pfx}:{m.group(2)}.{m.group(3)}")
        if b["kind"] == "table" and letter:
            tcount += 1
            labels.add(f"tab:{letter}.{tcount}")


# ---------------------------------------------------------------------------
# Inline conversion (pass 2)
# ---------------------------------------------------------------------------
YEARS_RE = r"\d{4}[a-z]?(?:,\s*\d{4}[a-z]?)*"
ID_RULES = [
    (re.compile(r"\bSC-(NOM|EDGE|PERT|FRONT)-(\d{2})\b"), lambda m: rf"\scn{{{m.group(1)}-{m.group(2)}}}"),
    (re.compile(r"\bSR-(\d{3})\b"), lambda m: rf"\sr{{{m.group(1)}}}"),
    (re.compile(r"\bH-(\d{2})\b"), lambda m: rf"\hz{{{m.group(1)}}}"),
    (re.compile(r"\bC-(0\d)\b"), lambda m: rf"\cagerule{{{m.group(1)}}}"),
    (re.compile(r"\bM-([A-Z]\d+)\b"), lambda m: rf"\met{{{m.group(1)}}}"),
    (re.compile(r"\bD-(\d{2})\b"), lambda m: rf"\dec{{{m.group(1)}}}"),
    # any other hyphenated upper-case label (TBD-Q10, ODD-3, SR-CL-A, GE4-V2, M-3):
    # an identifier too, so it must not break at its hyphen either
    (re.compile(r"(?<![\w-])([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)(?![\w-])"), lambda m: rf"\mbox{{{m.group(1)}}}"),
]
ID_TOKEN_RE = re.compile(r"^(SC-[A-Z]+-\d{2}|SR-\d{3}|H-\d{2}|C-0\d|M-[A-Z]\d+|D-\d{2}"
                         r"|[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)\W*$")

GREEK = {"α": "alpha", "β": "beta", "γ": "gamma", "δ": "delta", "ε": "varepsilon", "η": "eta",
         "θ": "theta", "κ": "kappa", "λ": "lambda", "μ": "mu", "π": "pi", "ρ": "rho", "σ": "sigma",
         "τ": "tau", "φ": "phi", "ψ": "psi", "ω": "omega", "Δ": "Delta", "Σ": "Sigma", "Ω": "Omega"}
SYMBOLS = {"≈": r"\approx", "→": r"\rightarrow", "←": r"\leftarrow", "↔": r"\leftrightarrow",
           "⇒": r"\Rightarrow", "×": r"\times", "−": "-", "≤": r"\le", "≥": r"\ge", "±": r"\pm",
           "∧": r"\wedge", "·": r"\cdot", "∞": r"\infty", "≠": r"\neq", "∮": r"\oint"}
SUPERSCRIPTS = {"⁰": "0", "¹": "1", "²": "2", "³": "3", "⁴": "4", "⁵": "5", "⁶": "6", "⁷": "7",
                "⁸": "8", "⁹": "9", "⁻": "$-$"}
TEXT_ESCAPES = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "&": r"\&", "%": r"\%",
                "$": r"\$", "#": r"\#", "_": r"\_", "~": r"$\sim$", "^": r"\textasciicircum{}"}


class Inline:
    def __init__(self, labels: set[str], bib: list[BibEntry], doc_rel: str = ""):
        self.labels = labels
        self.doc_rel = doc_rel
        self.by_name: dict[str, dict[str, str]] = {}
        for e in bib:
            self.by_name.setdefault(e.first, {})[e.label_year] = e.key
        self.cited: set[str] = set()

    # -- citations ---------------------------------------------------------
    def _keys(self, names: str, years: list[str]) -> list[str] | None:
        names = names.strip()
        if not names or not (names[0].isupper()):
            return None
        first = re.split(r",\s*|\s+and\s+|\s+&\s+", re.sub(r"\s+et al\.?$", "", names))[0]
        table = self.by_name.get(norm_name(first))
        if not table:
            return None
        keys = []
        for y in years:
            if y not in table:
                return None
            keys.append(table[y])
        return keys

    def citations(self, s: str, put) -> str:
        def paren(m):
            lead, content = m.group(1), m.group(2)
            parts = [p.strip() for p in content.split(";")]
            rendered, pure, all_keys = [], True, []
            for p in parts:
                pm = re.match(rf"^(.*?),\s*({YEARS_RE})$", p)
                if not pm:
                    return m.group(0)
                words, years = pm.group(1).split(" "), re.split(r",\s*", pm.group(2))
                for k in range(len(words)):
                    keys = self._keys(" ".join(words[k:]), years)
                    if keys:
                        break
                else:
                    if re.search(r"[A-Z]", pm.group(1)):
                        warn(f"{self.doc_rel}: unresolved citation '({content})'")
                    return m.group(0)
                self.cited.update(keys)
                all_keys += keys
                if k:
                    pure = False
                rendered.append((" ".join(words[:k]), " ".join(words[k:]), keys))
            if pure:
                return lead.replace(" ", "") + put(("~" if lead else "") + r"\cite{" + ",".join(all_keys) + "}")
            out = []
            for prefix, names, keys in rendered:
                out.append((prefix + " " if prefix else "") + names + put(r"~\cite{" + ",".join(keys) + "}"))
            return lead + "(" + "; ".join(out) + ")"

        s = re.sub(rf"(\s?)\(([^()]*?[A-Za-z][^()]*?,\s*{YEARS_RE})\)", paren, s)

        out, pos = [], 0
        for m in re.finditer(rf"\s\(({YEARS_RE})\)", s):
            before = s[pos:m.start()]
            words = before.split(" ")
            years = re.split(r",\s*", m.group(1))
            for k in range(1, min(6, len(words)) + 1):
                keys = self._keys(" ".join(words[-k:]), years)
                if keys:
                    self.cited.update(keys)
                    out.append(before + put(r"~\cite{" + ",".join(keys) + "}"))
                    break
            else:
                warn(f"{self.doc_rel}: year in parentheses not resolved as a citation: "
                     f"'...{before[-40:]} ({m.group(1)})'")
                out.append(s[pos:m.end()])
            pos = m.end()
        out.append(s[pos:])
        return "".join(out)

    # -- cross references ---------------------------------------------------
    def xrefs(self, s: str, put) -> str:
        def ref(label: str, text: str, prefix: str = "") -> str:
            if label in self.labels:
                return put(prefix + r"\ref{" + label + "}")
            if not re.fullmatch(r"sec:\d+", label):    # "TR 5469 §7" is a clause of the standard
                warn(f"{self.doc_rel}: reference '{text}' has no target ({label})")
            return text

        def chapters(m):
            word, a, sep, b = m.group(1), m.group(2), m.group(3), m.group(4)
            out = word + ref(f"ch:{int(a):02d}", " " + a, "~")
            if b:
                out += sep + ref(f"ch:{int(b):02d}", b)
            return out

        s = re.sub(r"\b([Cc]hapters?)\s+(\d{1,2})\b(?:(\s*–\s*|\s+and\s+|\s+to\s+)(\d{1,2})\b)?", chapters, s)
        s = re.sub(r"\b(Figure|Table)\s+([A-I]|\d{1,2})\.(\d{1,2})\b",
                   lambda m: m.group(1) + ref(f"{'fig' if m.group(1) == 'Figure' else 'tab'}:"
                                              f"{m.group(2)}.{m.group(3)}", " " + m.group(2) + "." + m.group(3), "~"),
                   s)
        s = re.sub(r"\bAppendix\s+([A-I])\b", lambda m: "Appendix" + ref(f"app:{m.group(1)}", " " + m.group(1), "~"), s)
        s = re.sub(r"§([A-I0-9]{1,2}(?:\.\d+)*)", lambda m: ref(f"sec:{m.group(1)}", "§" + m.group(1), r"\S"), s)
        return s

    # -- code spans -------------------------------------------------------------
    @staticmethod
    def code(content: str) -> str:
        if content == "NOT SATISFIED":
            return r"\verdictnot{}"
        if content == "SATISFIED":
            return r"\verdictsat{}"
        out = []
        long_token = False
        for i, ch in enumerate(content):
            if i == 0 or content[i - 1] == " ":
                long_token = len(content[i:].split(" ", 1)[0]) > CODE_BREAK_LEN
            if ch == "\x01":
                out.append("|")
            elif ch == "_":
                out.append(r"\_\allowbreak{}" if long_token else r"\_")
            elif ch in "/.(," and long_token:
                out.append(ch + r"\allowbreak{}")
            elif ch in TEXT_ESCAPES and ch != "~":
                out.append(TEXT_ESCAPES[ch])
            elif ch == "~":
                out.append(r"\textasciitilde{}")
            else:
                out.append(ch)
        return r"\texttt{" + "".join(out) + "}"

    # -- the pipeline ---------------------------------------------------------
    def convert(self, s: str) -> str:
        store: list[str] = []

        def put(latex: str) -> str:
            store.append(latex)
            return f"\x00{len(store) - 1}\x00"

        s = s.replace("&nbsp;", " ").replace("\\|", "\x01")
        s = re.sub(r"`([^`]+)`", lambda m: put(self.code(m.group(1))), s)
        s = self.citations(s, put)
        s = self.xrefs(s, put)
        for rx, fn in ID_RULES:
            s = rx.sub(lambda m, fn=fn: put(fn(m)), s)
        s = "".join(TEXT_ESCAPES.get(ch, ch) for ch in s)
        s = s.replace("\x01", r"\textbar{}")
        s = re.sub(r"(\d) \\%", r"\1\\,\\%", s)
        s = re.sub(r"[⁰¹²³⁴⁵⁶⁷⁸⁹⁻]+", lambda m: r"\textsuperscript{" + "".join(SUPERSCRIPTS[c] for c in m.group(0)) + "}", s)
        s = s.replace("$-$1", "$-1$")
        for ch, name in GREEK.items():
            s = s.replace(ch, rf"$\{name}$")
        for ch, cmd in SYMBOLS.items():
            s = s.replace(ch, f"${cmd}$")
        s = s.replace("✓", r"\ding{51}").replace("✗", r"\ding{55}").replace("…", r"\ldots{}")
        # "gymnasium–Gazebo–ROS2": an en dash between words is not a break point
        # for TeX, and the compound is wider than a line of the text column
        s = re.sub(r"(?<=[A-Za-z])–(?=[A-Za-z])", r"–\\allowbreak{}", s)
        s = re.sub(r"(?<!\\)\$\$", "", s)     # merge adjacent maths: "$\sigma$$\theta$" -> "$\sigma\theta$"
        s = re.sub(r'"([^"]+)"', r"\\enquote{\1}", s)
        s = re.sub(r"“([^”]+)”", r"\\enquote{\1}", s)
        s = re.sub(r"(?<![\w\\])'([^'\s][^']*?)'(?!\w)", r"\\enquote*{\1}", s)
        s = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", s)
        s = re.sub(r"(?<![\w\\*])\*(?=\S)(.+?)(?<=\S)\*(?![\w*])", r"\\emph{\1}", s)
        if "*" in re.sub(r"\x00\d+\x00|\\enquote\*", "", s):
            warn(f"{self.doc_rel}: stray '*' after emphasis conversion: {s[:80]}")
        s = re.sub(r"(\x00\d+\x00)/", r"\1/\\allowbreak{}", s)   # C-04/C-06/C-03 may break at a slash
        while "\x00" in s:
            s = re.sub(r"\x00(\d+)\x00", lambda m: store[int(m.group(1))], s)
        return s


def plain(s: str) -> str:
    """Approximate the visible text of a Markdown cell, for width estimates."""
    s = s.replace("\\|", "|")
    s = re.sub(r"\((?:[^()]*?,\s*)?\d{4}[a-z]?(?:,\s*\d{4}[a-z]?)*\)", "[Xyz99]", s)
    return re.sub(r"[*`]", "", s).strip()


def short_caption(text: str) -> str:
    """First sentence of a caption, for the list of figures/tables."""
    depth = 0
    for i, ch in enumerate(text):
        if ch in "(`":
            depth += 1 if ch == "(" else 0
        elif ch == ")":
            depth = max(0, depth - 1)
        if ch == "." and depth == 0 and (i + 1 == len(text) or text[i + 1] == " ") and i > 20:
            return text[:i + 1]
    return text


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------
def split_row(row: str) -> list[str]:
    row = row.replace("\\|", "\x02")
    cells = [c.strip().replace("\x02", "\\|") for c in row.strip().strip("|").split("|")]
    return cells


CODE_BREAK_LEN = 16     # code tokens longer than this may break after _ / . ( ,
CODE_BREAK_AFTER = r"(?<=[_/.(,])"
HYPHENATE_MIN = 10      # prose words longer than this may be hyphenated in a table cell


def unbreakable_len(cell: str, header: bool = False) -> int:
    """Longest run a cell can NOT break inside: identifiers, short code tokens,
    and -- for prose -- words up to HYPHENATE_MIN characters (longer ones
    hyphenate). Header words never hyphenate."""
    longest = 1.0
    for m in re.finditer(r"`([^`]+)`", cell):
        for t in m.group(1).split():
            parts = [t] if len(t) <= CODE_BREAK_LEN else re.split(CODE_BREAK_AFTER, t)
            longest = max(longest, max(len(p) for p in parts) * 1.1)   # Iosevka: every glyph 0.415 em
    prose = re.sub(r"`[^`]+`", " ", cell)
    for t in re.split(r"[\s/]+", plain(prose)):
        if not t:
            continue
        if ID_TOKEN_RE.match(t) or header:
            longest = max(longest, vis_len(t))
        else:
            for p in re.split(r"(?<=[-–])", t):
                longest = max(longest, vis_len(p) if len(p) <= HYPHENATE_MIN else HYPHENATE_MIN)
    return longest


def vis_len(s: str) -> float:
    """Length in average characters: capitals and figures are wider."""
    return sum(1.45 if c.isupper() else 1.05 if c.isdigit() else 1.0 for c in s)


def table_height(rows_len, widths, cw):
    """Estimated height in text lines: each row is as tall as its tallest cell."""
    height = 0.0
    for r in rows_len:
        lines = [n * cw * 1.08 / max(w - 0.8, 1.0) for n, w in zip(r, widths)]
        # the tallest cell sets the row; a small share of the other cells keeps
        # a column that is never the tallest from being squeezed to its minimum
        height += max(lines) + 0.35 + 0.08 * sum(lines)
    return height


def rotatable(header, rows):
    """Columns of short marks (check marks, "partial", "30/30") under a long
    header: the header is what makes them wide, so it is set rotated."""
    body = [max((len(plain(r[j])) for r in rows), default=0) for j in range(len(header))]
    cand = [body[j] <= 8 and len(plain(header[j])) >= 6 and len(plain(header[j])) > body[j]
            for j in range(len(header))]
    # rotate a block of mark columns, never a lone column (a rotated "Assumption"
    # over S1..S5 reads worse than a wrapped one)
    if sum(cand) < 2 or not any(c and len(plain(h)) > 9 for c, h in zip(cand, header)):
        return [False] * len(header)
    return cand


def layout_widths(header, rows, width_mm, size, rotate=None):
    """Column widths that minimise the estimated table height.

    Every column starts at the width of its longest unbreakable run; the
    remaining space is handed out in small steps to whichever column shortens
    the table most. A column never grows past its longest cell, so short
    columns (IDs, S/E/C ratings, check marks) stay tight and the prose columns
    get the room."""
    cw = CHAR_MM[size]
    ncol = len(header)
    content = width_mm - 2 * SEP_MM * (ncol - 1) - 1.0     # 1 mm reserve against rounding
    rotate = rotate or [False] * ncol
    rows_len = [[len(plain(c)) for c in r] for r in rows] + \
        [[0 if rot else len(plain(h)) * 1.3 for h, rot in zip(header, rotate)]]
    maxc = [max(r[j] for r in rows_len) * cw + 1.0 for j in range(ncol)]
    minc = [max([unbreakable_len(r[j]) for r in rows] +
                [3 if rotate[j] else unbreakable_len(header[j], True) * 1.3]) * cw + 1.0
            for j in range(ncol)]
    maxc = [max(a, b) for a, b in zip(maxc, minc)]
    if sum(maxc) <= content:
        return "natural", maxc
    if sum(minc) > content:
        return "overflow", minc
    widths = list(minc)
    step = 0.5
    spare = content - sum(widths)
    while spare > 1e-6:
        inc = min(step, spare)
        base = table_height(rows_len, widths, cw)
        best, gain = None, 0.0
        for j in range(ncol):
            if widths[j] + inc > maxc[j] + 1e-6:
                continue
            trial = widths[:]
            trial[j] += inc
            g = base - table_height(rows_len, trial, cw)
            if g > gain + 1e-9:
                best, gain = j, g
        if best is None:
            # nothing shortens the table any more: widen the columns that are
            # furthest from their natural width, proportionally
            room = [maxc[j] - widths[j] for j in range(ncol)]
            if sum(room) <= 1e-6:
                room = [1.0] * ncol
            widths = [w + spare * r / sum(room) for w, r in zip(widths, room)]
            break
        widths[best] += inc
        spare -= inc
    return "fixed", widths


def estimate_height(header, rows, widths, size):
    cw, lh = CHAR_MM[size], LINE_MM[size]
    total = 0.0
    for r in [header] + rows:
        lines = max(math.ceil(len(plain(c)) * cw * 1.08 / max(w - 1.0, 1.0)) or 1 for c, w in zip(r, widths))
        total += lines * lh + 0.8
    return total


def column_spec(aligns, widths, kind):
    spec = []
    for a, w in zip(aligns, widths):
        if kind == "natural":
            spec.append({"c": "c", "r": "r"}.get(a, "l"))
        else:
            ragged = {"c": r"\centering", "r": r"\RaggedLeft"}.get(a, r"\RaggedRight")
            spec.append(rf">{{{ragged}\arraybackslash}}p{{{w:.1f}mm}}")
    return "@{}" + "".join(spec) + "@{}"


def layout_widths_rot(header, rows, width_mm, size):
    kind, widths = layout_widths(header, rows, width_mm, size)
    rot = rotatable(header, rows)
    if kind != "natural" and any(rot):
        kind, widths = layout_widths(header, rows, width_mm, size, rot)
        return kind, widths, rot
    return kind, widths, [False] * len(header)


def layout_table(header, rows, aligns, where):
    """Pick container, font size and column widths from the content.

    where: 'body'     -- a float; text column if it fits, else table* over
                         text + margin column
           'appendix' -- longtable over the full-width appendix geometry
           'front'    -- longtable inside the text column
    """
    if where == "body":
        kind, widths = layout_widths(header, rows, TEXT_MM, "small")
        if kind == "natural":
            return dict(env="table", size="small", kind=kind, widths=widths, width=TEXT_MM,
                        rotate=[False] * len(header))
        for size in ("small", "footnotesize", "scriptsize"):
            kind, widths, rot = layout_widths_rot(header, rows, WIDE_MM, size)
            if kind != "overflow" and estimate_height(header, rows, widths, size) < PAGE_TEXT_MM * 0.8:
                return dict(env="table*", size=size, kind=kind, widths=widths, width=WIDE_MM, rotate=rot)
        warn(f"body table with header {header[:3]} is too large for one float")
        return dict(env="table*", size="scriptsize", kind=kind, widths=widths, width=WIDE_MM, rotate=rot)
    width = APPX_MM if where == "appendix" else TEXT_MM
    sizes = ("small", "footnotesize", "scriptsize") if where == "appendix" else ("small", "footnotesize")
    for size in sizes:
        kind, widths, rot = layout_widths_rot(header, rows, width, size)
        if kind == "natural" or (kind == "fixed" and size != "small"):
            # a table that fits comfortably on one page is better as a float:
            # a longtable never floats, so it drags half-empty pages behind it
            short = where == "appendix" and estimate_height(header, rows, widths, size) < PAGE_TEXT_MM * 0.5
            return dict(env="table" if short else "longtable", size=size, kind=kind, widths=widths,
                        width=width, rotate=rot)
    return dict(env="longtable", size=sizes[-1], kind=kind, widths=widths, width=width, rotate=rot)


def render_table(inline: Inline, header, rows, aligns, where, caption=None, short=None, label=None):
    plan = layout_table(header, rows, aligns, where)
    if plan["kind"] == "overflow":
        warn(f"{inline.doc_rel}: table {label or header[:2]} cannot fit even at {plan['size']}")
    spec = column_spec(aligns, plan["widths"], "natural" if plan["kind"] == "natural" else "fixed")
    n = len(header)
    head = " & ".join(
        "" if not h else
        (r"\rotatebox{90}{\tabhead{" + inline.convert(h) + "}}" if rot else r"\tabhead{" + inline.convert(h) + "}")
        for h, rot in zip(header, plan["rotate"])) + r" \\"
    multiline = plan["kind"] != "natural" and estimate_height(header, rows, plan["widths"], plan["size"]) > \
        (len(rows) + 1) * (LINE_MM[plan["size"]] + 0.8) * 1.3
    body = []
    for r in rows:
        body.append("  " + " & ".join(inline.convert(c) for c in r) + r" \\")
        if multiline:
            body.append(r"  \addlinespace[2pt]")
    if multiline and body:
        body.pop()
    cap = ""
    if caption:
        cap = r"\caption" + (f"[{inline.convert(short)}]" if short and short != caption else "") + \
            "{" + inline.convert(caption) + "}" + (r"\label{" + label + "}" if label else "")
    size = "\\" + plan["size"]
    out = [f"% layout: {plan['env']}, {plan['kind']}, \\{plan['size']}, "
           f"{sum(plan['widths']) + 2 * SEP_MM * (n - 1):.0f} of {plan['width']:.0f} mm"]
    if plan["env"] == "longtable":
        out += [r"\begingroup", size + rf"\setlength{{\tabcolsep}}{{{TABCOLSEP_PT:g}pt}}",
                r"\setlength{\LTleft}{0pt}\setlength{\LTright}{\fill}\setlength{\LTcapwidth}{\textwidth}",
                rf"\begin{{longtable}}{{{spec}}}"]
        if cap:
            out.append(cap + r" \\")
        out += [r"  \toprule", "  " + head, r"  \midrule", r"  \endfirsthead",
                rf"  \multicolumn{{{n}}}{{@{{}}l}}{{\emph{{(continued)}}}} \\",
                r"  \toprule", "  " + head, r"  \midrule", r"  \endhead",
                r"  \midrule", rf"  \multicolumn{{{n}}}{{r@{{}}}}{{\emph{{(continued on next page)}}}} \\",
                r"  \endfoot", r"  \bottomrule", r"  \endlastfoot"]
        out += body
        out += [r"\end{longtable}", r"\endgroup"]
    else:
        env = plan["env"]
        # appendices: the table belongs right where the register text calls it
        out += [rf"\begin{{{env}}}[{'!htbp' if where == 'appendix' else 'htbp'}]"]
        if cap:
            out.append(cap)
        out += [size + rf"\setlength{{\tabcolsep}}{{{TABCOLSEP_PT:g}pt}}", rf"\begin{{tabular}}{{{spec}}}",
                r"  \toprule", "  " + head, r"  \midrule"]
        out += body
        out += [r"  \bottomrule", r"\end{tabular}", rf"\end{{{env}}}"]
    return "\n".join(out)


def parse_table(block, supplied_header=None):
    rows = [split_row(r) for r in block["rows"]]
    if supplied_header:
        header, data, aligns = supplied_header, rows, ["l"] * len(supplied_header)
    else:
        header, sep, data = rows[0], rows[1], rows[2:]
        aligns = []
        for c in sep:
            c = c.strip()
            aligns.append("c" if c.startswith(":") and c.endswith(":") else "r" if c.endswith(":") else "l")
    n = len(header)
    data = [(r + [""] * n)[:n] for r in data]
    return header, data, aligns


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
def render_figure(inline: Inline, img, caption, label, where):
    rel = img["src"].replace("../figures/", "")
    if not (FIG_POOL / rel).exists():
        warn(f"{inline.doc_rel}: figure file missing: {rel}")
    alt = re.sub(r"^Figure\s+[A-Z0-9]+\.\d+\s+—\s+", "", img["alt"]).strip()
    docx_mm = img["width"] * 159.2 / 602.0      # width the DOCX build gives it
    if where == "appendix":
        env, width = "figure", f"{min(1.0, docx_mm / APPX_MM):.2f}\\textwidth"
    elif docx_mm <= TEXT_MM * 1.08:
        env, width = "figure", f"{min(1.0, docx_mm / TEXT_MM):.2f}\\textwidth"
    else:
        env, width = "figure*", f"{min(1.0, docx_mm / WIDE_MM):.2f}\\widefigurewidth"
    cap = inline.convert(caption)
    return "\n".join([
        rf"\begin{{{env}}}[{'!htbp' if where == 'appendix' else 'htbp'}]",
        rf"  \includegraphics[width={width}]{{{rel}}}",
        rf"  \caption[{inline.convert(alt)}]{{{cap}}}\label{{{label}}}",
        rf"\end{{{env}}}",
    ])


# ---------------------------------------------------------------------------
# Rendering a document
# ---------------------------------------------------------------------------
def load_margin_notes() -> dict[str, list[dict]]:
    """Parse margin_notes.md: '## <file>' sections of '@ <anchor>' entries."""
    notes: dict[str, list[dict]] = {}
    path = HERE / "margin_notes.md"
    if not path.exists():
        return notes
    current = None
    entry = None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^## (body/\S+\.md)\s*$", line)
        if m:
            current = notes.setdefault(m.group(1), [])
            entry = None
            continue
        if current is None:
            continue
        m = re.match(r"^@(prelim)?\s+(.+?)\s*$", line)
        if m:
            entry = dict(kind="prelim" if m.group(1) else "note", anchor=m.group(2), text="", used=False)
            current.append(entry)
        elif not line.strip():
            entry = None
        elif entry is not None:
            entry["text"] = (entry["text"] + " " + line.strip()).strip()
    return notes


MARGIN_NOTES = load_margin_notes()

HEADER = ("% GENERATED by md2tex.py from ../draft_v5_en/{src} -- do not edit by hand.\n"
          "% Change the Markdown and run `python md2tex.py`; edits here are overwritten.\n")


def render_doc(doc: Doc, labels: set[str], bib: list[BibEntry]) -> tuple[str, set[str]]:
    inline = Inline(labels, bib, doc.rel)
    letter = doc.md.name[0] if doc.kind == "appendix" else None
    where = {"chapter": "body", "appendix": "appendix", "front": "front"}[doc.kind]
    plan = {id(b): (cmd, title, label) for b, cmd, title, label in heading_plan(doc)}
    out = [HEADER.format(src=doc.rel)]
    if letter and any(k[0] == letter for k in SUPPLIED_TABLE_HEADERS):
        out.append("% NOTE: the source tables carry no header row; the headers below are supplied\n"
                   "% by md2tex.py (SUPPLIED_TABLE_HEADERS) from the column contents.\n")
    blocks = doc.blocks
    tcount = 0
    skip = set()
    front_name = doc.md.stem
    notes = MARGIN_NOTES.get(doc.rel, [])

    def running(text: str) -> str:
        """Convert running text, attaching the margin notes anchored in it."""
        markers = {}
        for n in notes:
            if n["used"]:
                continue
            at = text.find(n["anchor"])
            if at < 0:
                continue
            end = at + len(n["anchor"])
            while end < len(text) and text[end] == "*":     # land after a closing ** or *
                end += 1
            key = f"\x03{len(markers)}\x03"
            text = text[:end] + key + text[end:]
            markers[key] = n
            n["used"] = True
        latex = inline.convert(text)
        for key, n in markers.items():
            tex = r"\prelimflag{}" if n["kind"] == "prelim" else r"\sidenote{" + inline.convert(n["text"]) + "}"
            if key not in latex:
                warn(f"{doc.rel}: margin note lost in conversion: '{n['anchor']}'")
            latex = latex.replace(key, tex)
        return latex

    for i, b in enumerate(blocks):
        if i in skip:
            continue
        k = b["kind"]
        if k == "heading":
            cmd, title, label = plan[id(b)]
            if doc.kind == "front" and front_name in ("10_abstract", "15_preface", "05_declaration"):
                continue
            t = inline.convert(title)
            short = re.sub(r"[*`]", "", title)
            opt = f"[{inline.convert(short)}]" if t != inline.convert(short) else ""
            out.append(f"\\{cmd}{opt}{{{t}}}" + (f"\n\\label{{{label}}}" if label else "") + "\n")
        elif k == "para":
            m = CAPTION_RE.match(b["text"])
            if m:
                continue        # consumed by the figure/table before it
            out.append(running(b["text"]) + "\n")
        elif k == "img":
            nxt = blocks[i + 1] if i + 1 < len(blocks) else None
            m = CAPTION_RE.match(nxt["text"]) if nxt and nxt["kind"] == "para" else None
            if not m:
                warn(f"{doc.rel}: image {b['src']} has no caption paragraph")
                continue
            label = f"fig:{m.group(2)}.{m.group(3)}"
            out.append(render_figure(inline, b, m.group(4), label, where) + "\n")
            skip.add(i + 1)
        elif k == "table":
            tcount += 1
            supplied = SUPPLIED_TABLE_HEADERS.get((letter, tcount)) if letter else None
            header, rows, aligns = parse_table(b, supplied)
            nxt = blocks[i + 1] if i + 1 < len(blocks) else None
            caption = short = label = None
            if nxt and nxt["kind"] == "para":
                m = CAPTION_RE.match(nxt["text"])
                if m and m.group(1) == "Table":
                    caption = m.group(4)
                    label = f"tab:{m.group(2)}.{m.group(3)}"
                    skip.add(i + 1)
                elif re.fullmatch(r"\*[^*].*[^*]\*", nxt["text"]):
                    caption = nxt["text"][1:-1]
                    skip.add(i + 1)
            if letter:
                label = f"tab:{letter}.{tcount}"
                if caption is None:
                    caption = SUPPLIED_TABLE_CAPTIONS.get((letter, tcount))
                    if caption is None:
                        warn(f"{doc.rel}: table {tcount} has no caption")
            if caption:
                short = short_caption(caption)
            out.append(render_table(inline, header, rows, aligns, where, caption, short, label) + "\n")
        elif k == "quote":
            paras = [running(p) for p in b["paras"]]
            out.append("\\begin{quote}\n" + "\n\n".join(paras) + "\n\\end{quote}\n")
        elif k == "list":
            env = "enumerate" if b["ordered"] else "itemize"
            items = "\n".join("  \\item " + running(it) for it in b["items"])
            out.append(f"\\begin{{{env}}}\n{items}\n\\end{{{env}}}\n")
        elif k == "code":
            size = r"\footnotesize" if len(b["lines"]) > 20 else r"\small"
            body = "\n".join(b["lines"])
            out.append("\\begingroup\n" + size + "\n\\begin{verbatim}\n" + body + "\n\\end{verbatim}\n\\endgroup\n")
    text = "\n".join(out)
    if front_name == "05_declaration":
        text = render_declaration(doc, inline)
    return text, inline.cited


def render_declaration(doc: Doc, inline: Inline) -> str:
    paras = [b["text"] for b in doc.blocks if b["kind"] == "para"]
    body, place, name = paras[0], paras[1], paras[2]
    return HEADER.format(src=doc.rel) + "\n".join([
        r"\begin{declaration}",
        r"\addchaptertocentry{\authorshipname}",
        "",
        r"\noindent " + inline.convert(body),
        "",
        r"\bigskip\bigskip",
        "",
        r"\noindent",
        r"\begin{tabular}[b]{@{}l@{}}",
        "\t" + inline.convert(place),
        r"\end{tabular}",
        r"\hspace{\fill}",
        r"\begin{tabular}[b]{@{}l@{}}",
        "\t\\rule{42mm}{0.4pt}\\\\",
        "\t" + inline.convert(name),
        r"\end{tabular}",
        "",
        r"\end{declaration}",
        "",
    ])


# ---------------------------------------------------------------------------
# Figures for a self-contained project / Overleaf
# ---------------------------------------------------------------------------
def referenced_figures() -> list[str]:
    names = set()
    for tex in list((HERE / "chapters").glob("*.tex")) + list((HERE / "appendices").glob("*.tex")) + \
            list((HERE / "front").glob("*.tex")):
        names.update(re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", tex.read_text(encoding="utf-8")))
    return sorted(names)


def collect_figures(dest: Path) -> list[str]:
    copied = []
    for rel in referenced_figures():
        src = FIG_POOL / rel
        if not src.exists():
            warn(f"figure not found in pool: {rel}")
            continue
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)
        copied.append(rel)
    return copied


def write_zip() -> None:
    figs = HERE / "figures"
    collect_figures(figs)
    include = ["main.tex", "PSIThesis.cls", "literature.bib", "latexmkrc", "Makefile", "deps.txt", "README.md"]
    dirs = ["misc", "front", "chapters", "appendices", "fonts", "figures"]
    with zipfile.ZipFile(ZIP_OUT, "w", zipfile.ZIP_DEFLATED) as z:
        for name in include:
            z.write(HERE / name, name)
        for d in dirs:
            for p in sorted((HERE / d).rglob("*")):
                if p.is_file() and p.suffix not in (".aux", ".log"):
                    z.write(p, p.relative_to(HERE).as_posix())
    print(f"wrote {ZIP_OUT} ({ZIP_OUT.stat().st_size / 1e6:.1f} MB)")


# ---------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--figures", action="store_true", help="copy referenced figures into ./figures")
    ap.add_argument("--zip", action="store_true", help="write ../thesis-psithesis-overleaf.zip")
    args = ap.parse_args()

    bib = load_bibliography()
    docs = build_docs()
    labels: set[str] = set()
    for d in docs:
        for _b, cmd, _t, label in heading_plan(d):
            if label:
                labels.add(label)
        figure_and_table_labels(d, labels)

    cited: set[str] = set()
    for d in docs:
        text, c = render_doc(d, labels, bib)
        cited |= c
        target = HERE / d.out
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")

    bib_text = ["% literature.bib -- GENERATED by md2tex.py from ../draft_v5_en/back/0_bibliography.md.",
                "% Do not edit by hand. Keys: <first author surname><year><suffix>; standards by number.", ""]
    bib_text += [e.bibtex() + "\n" for e in bib]
    (HERE / "literature.bib").write_text("\n".join(bib_text), encoding="utf-8", newline="\n")

    for rel, entries in MARGIN_NOTES.items():
        for n in entries:
            if not n["used"]:
                warn(f"margin_notes.md: anchor not found in running text of {rel}: '{n['anchor']}'")

    uncited = [e.key for e in bib if e.key not in cited]
    if uncited:
        warn(f"bibliography entries never cited in the text (still printed via \\nocite): {uncited}")

    if args.figures or args.zip:
        n = len(collect_figures(HERE / "figures"))
        print(f"collected {n} figures into ./figures")
    if args.zip:
        write_zip()

    print(f"{len(docs)} files and literature.bib ({len(bib)} entries) written")
    for w in WARNINGS:
        print("WARNING:", w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
