"""Generate oval centerline polyline for lane_following.world.

Geometry:
    Two straight segments along X at y = ±R, length L each.
    Two semicircles of radius R, centred at (±L/2, 0).

Direction: clockwise when viewed from +z (start top-left, go right along
the top, curve down the right, leftward along bottom, curve up the left).
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import List, Tuple

import yaml


def generate_oval(
    straight_length: float = 1.5,
    radius: float = 0.75,
    segment_length: float = 0.1,
) -> List[Tuple[float, float]]:
    """Oval centerline polyline: two straights joined by two semicircular arcs."""
    half_l = straight_length / 2.0

    n_straight = max(2, int(round(straight_length / segment_length)))
    n_curve = max(4, int(round(math.pi * radius / segment_length)))

    points: List[Tuple[float, float]] = []

    for i in range(n_straight):
        x = -half_l + i * (straight_length / n_straight)
        points.append((x, radius))

    for i in range(n_curve):
        theta = math.pi / 2.0 - i * (math.pi / n_curve)
        x = half_l + radius * math.cos(theta)
        y = radius * math.sin(theta)
        points.append((x, y))

    for i in range(n_straight):
        x = half_l - i * (straight_length / n_straight)
        points.append((x, -radius))

    for i in range(n_curve):
        theta = -math.pi / 2.0 - i * (math.pi / n_curve)
        x = -half_l + radius * math.cos(theta)
        y = radius * math.sin(theta)
        points.append((x, y))

    points.append(points[0])
    return points


def to_yaml_dict(
    points: List[Tuple[float, float]],
    lane_width: float,
    road_width: float,
    straight_length: float,
    radius: float,
) -> dict:
    """Wrap the points + lane/road widths in the centerline YAML schema."""
    perimeter = 2.0 * straight_length + 2.0 * math.pi * radius
    return {
        "centerline": {
            "geometry": "oval_clockwise",
            "straight_length_m": straight_length,
            "curve_radius_m": radius,
            "perimeter_m": round(perimeter, 4),
            "num_points": len(points),
            "points": [[round(x, 4), round(y, 4)] for x, y in points],
        },
        "lane_width": lane_width,
        "road_width": road_width,
    }


def main() -> None:
    """CLI entry: generate the oval centerline YAML."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/cobraflex_rl/config/oval_centerline.yaml"),
    )
    parser.add_argument("--straight-length", type=float, default=1.5)
    parser.add_argument("--radius", type=float, default=0.75)
    parser.add_argument("--segment-length", type=float, default=0.1)
    parser.add_argument("--lane-width", type=float, default=0.245)
    parser.add_argument("--road-width", type=float, default=0.50)
    args = parser.parse_args()

    points = generate_oval(
        straight_length=args.straight_length,
        radius=args.radius,
        segment_length=args.segment_length,
    )
    payload = to_yaml_dict(
        points=points,
        lane_width=args.lane_width,
        road_width=args.road_width,
        straight_length=args.straight_length,
        radius=args.radius,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by scripts/generate_oval_centerline.py.\n"
            "# Re-run that script to regenerate after changing geometry.\n"
            "# Coordinates in metres; clockwise viewed from +z; closing\n"
            "# point repeats the first.\n\n"
        )
        yaml.safe_dump(payload, handle, sort_keys=False)

    print(f"Wrote {len(points)} points to {args.output}")
    print(f"Perimeter: {payload['centerline']['perimeter_m']:.4f} m")


if __name__ == "__main__":
    main()
