#!/usr/bin/env python3
"""Build a single self-contained URDF for Isaac Sim from the cobraflex xacro.

The simulation robot (``src/cobraflex/urdf/my_robot_gazebo_mesh.urdf``) is a
xacro that pulls in two external files:

  * ``inertial_macros.xacro`` -- material + inertia macros (kept; expanded inline)
  * ``robot.gazebo``          -- Gazebo/gz plugins + sensors (NOT needed by Isaac)

Isaac Sim's URDF importer ignores ``<gazebo>`` blocks but cannot resolve
``$(find ...)`` substitutions or xacro macros, and it rejects ``<visual>`` /
``<collision>`` elements that carry no ``<geometry>``. This tool produces one
flat ``.urdf`` that Isaac can import directly, with every kinematic / inertial /
material attribute of the source preserved:

  1. Run ``xacro`` to expand macros, properties and math.
  2. Drop all ``<gazebo>`` elements (Gazebo-only; Isaac brings its own physics).
  3. Rewrite mesh paths to ``../meshes/<file>`` so they resolve relative to the
     output URDF (no ROS / ament index needed).
  4. Strip empty ``<visual>``/``<collision>`` (geometry-less) elements.

Output: ``src/cobraflex/urdf/cobraflex_isaac.urdf`` (re-derivable; do not edit by
hand -- change the source xacro and re-run this script).

Usage:
    python tools/build_isaac_urdf.py
"""
from __future__ import annotations

import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_XACRO = REPO / "src/cobraflex/urdf/my_robot_gazebo_mesh.urdf"
OUT_URDF = REPO / "src/cobraflex/urdf/cobraflex_isaac.urdf"
# Mesh prefix relative to the output URDF location (urdf/ -> ../meshes/).
MESH_PREFIX = "../meshes"

GAZEBO_TAG = "gazebo"


def expand_xacro(src: Path) -> str:
    """Run xacro on *src* and return the expanded URDF as a string."""
    try:
        return subprocess.check_output(["xacro", str(src)], text=True)
    except FileNotFoundError:
        sys.exit("ERROR: 'xacro' not found. Source ROS2 first: "
                 "source /opt/ros/jazzy/setup.bash")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"ERROR: xacro failed: {exc}")


def strip_for_isaac(xml_text: str) -> ET.ElementTree:
    """Remove Gazebo blocks, fix mesh paths, drop empty visual/collision."""
    root = ET.fromstring(xml_text)

    # 1) Remove all <gazebo> children (plugins + sensors -> Gazebo only).
    for parent in root.iter():
        for child in list(parent):
            if child.tag == GAZEBO_TAG:
                parent.remove(child)
    # Top-level <gazebo> under <robot>.
    for child in list(root):
        if child.tag == GAZEBO_TAG:
            root.remove(child)

    # 2) Rewrite every mesh filename to a relative ../meshes/<basename> path.
    for mesh in root.iter("mesh"):
        fn = mesh.get("filename")
        if fn:
            mesh.set("filename", f"{MESH_PREFIX}/{Path(fn).name}")

    # 3) Drop <visual>/<collision> that carry no <geometry> (Isaac rejects them).
    for link in root.iter("link"):
        for tag in ("visual", "collision"):
            for elem in list(link.findall(tag)):
                if elem.find("geometry") is None:
                    link.remove(elem)

    # Drop the now-unused xacro namespace declaration if present.
    if "xmlns:xacro" in root.attrib:
        del root.attrib["xmlns:xacro"]

    return ET.ElementTree(root)


def main() -> None:
    if not SRC_XACRO.exists():
        sys.exit(f"ERROR: source xacro not found: {SRC_XACRO}")
    tree = strip_for_isaac(expand_xacro(SRC_XACRO))
    ET.indent(tree, space="  ")
    header = ("<?xml version=\"1.0\"?>\n"
              "<!-- GENERATED by tools/build_isaac_urdf.py from "
              "my_robot_gazebo_mesh.urdf - do not edit by hand. -->\n")
    body = ET.tostring(tree.getroot(), encoding="unicode")
    OUT_URDF.write_text(header + body + "\n")
    n_links = len(tree.getroot().findall("link"))
    n_joints = len(tree.getroot().findall("joint"))
    print(f"Wrote {OUT_URDF.relative_to(REPO)}  ({n_links} links, {n_joints} joints)")


if __name__ == "__main__":
    main()
